[package]
name = "clipboard_vanisher"
version = "0.1.0"
authors = ["sinasalek <sinasalek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
periodic = "0.1.1"
clipboard = "0.5.0"